### ISSUE TITLE
Breaks `this`

### ISSUE THREAD

**Issue by appsforartists** [twistdigital/es6-promisify#5]
If I try to `promisify` this function:

```javascript
WebpackDevServer.prototype.listen = function() {
	var listeningApp = this.listeningApp =
		this.app.listen.apply(this.app, arguments);
	this.io = socketio.listen(listeningApp, {
		"log level": 1
	});
	this.io.sockets.on("connection", function(socket) {
		if(this.hot) socket.emit("hot");
		if(!this._stats) return;
		this._sendStats(socket, this._stats.toJson());
	}.bind(this));
}
```

and then call it:

    self.webpackDevServer.listen(
      settings.WEBPACK_PORT,
      settings.HOST
    ).then(
    …

I get an error:

    [TypeError: Cannot read property 'listen' of undefined]

However, I do not have this problem when I use [prfun](https://github.com/cscott/prfun)'s implementation of `promisify`

**Comment by mikehall314** [comment]
Fixed in master
